# Generated by Django 4.2.6 on 2023-12-01 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import shared.custom_model_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{12}$')])),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('uuid', models.UUIDField(blank=True, default=uuid.UUID('400e7df4-91cc-4ecc-8159-0367c11b2081'), null=True, unique=True)),
                ('seen', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quantity_type', models.CharField(choices=[('SQUARE_METER', 'Square Meter'), ('NUMBER', 'Number')], default='NUMBER', max_length=50)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product')),
            ],
        ),
    ]
