# Generated by Django 4.2.6 on 2023-11-15 17:09

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_type',
            field=models.CharField(choices=[('SQUARE_METER', 'Square Meter'), ('NUMBER', 'Number')], default='NUMBER', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('1d7eb0ff-3708-4858-8cf2-281fe12cbbc0'), null=True, unique=True),
        ),
    ]
