# Generated by Django 4.2.6 on 2023-12-01 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('cf880709-f65b-47f5-9f70-c0061c734244'), null=True, unique=True),
        ),
    ]
