# Generated by Django 4.2.6 on 2024-01-23 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('edc582d4-c557-4b5c-b76f-95ca90895ede'), null=True, unique=True),
        ),
    ]
