# Generated by Django 4.2.6 on 2023-11-17 09:15

from django.db import migrations, models
import shared.custom_model_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_managers_orderitem_quantity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=shared.custom_model_fields.CreatedAtField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=shared.custom_model_fields.UpdatedAtField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0cc57d9c-c95a-4f55-b829-2e6425c1e757'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=shared.custom_model_fields.CreatedAtField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=shared.custom_model_fields.UpdatedAtField(auto_now=True),
        ),
    ]
