# Generated by Django 4.2.6 on 2023-11-17 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at_alter_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ebcabf2e-548f-448d-abd6-703ade050b79'), null=True, unique=True),
        ),
    ]
