# Generated by Django 4.2.6 on 2024-01-28 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('528e67a0-5c4d-4200-afc7-336f427bf9e7'), null=True, unique=True),
        ),
    ]
