# Generated by Django 4.2.6 on 2024-02-18 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('d8973481-f95c-4af1-90eb-9f5feaee68ea'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_type',
            field=models.CharField(choices=[('SQUARE_METER', 'Square Meter'), ('NUMBER', 'Number'), ('BOX', 'Box')], default='NUMBER', max_length=50),
        ),
    ]
