# Generated by Django 4.2.6 on 2023-11-17 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('77646a2e-1720-44e8-8c36-6f6be8fd902d'), null=True, unique=True),
        ),
    ]
