# Generated by Django 4.2.6 on 2024-04-21 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_uuid_alter_orderitem_quantity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('798ef2c1-efd1-4e11-9b99-cf5f1935236c'), null=True, unique=True),
        ),
    ]
