# Generated by Django 4.2.6 on 2023-11-28 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('9047c9be-1ff9-4a91-b52e-ef750f8eead4'), null=True, unique=True),
        ),
    ]
