# Generated by Django 4.2.6 on 2023-12-01 11:01

import apps.store.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields
import shared.custom_model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_image', models.ImageField(upload_to=apps.store.models.brand_image_path)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_image', models.ImageField(upload_to=apps.store.models.category_image_path)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.store.models.collection_image_path)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_brand', to='store.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_category', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity_type', models.CharField(choices=[('SQUARE_METER', 'Square Meter'), ('NUMBER', 'Number')], default='NUMBER', max_length=50)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_collection', to='store.collection')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', shared.custom_model_fields.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], default='az', max_length=2)),
                ('text', shared.custom_model_fields.TextUploadingField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_information', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.store.models.product_image_path)),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='store.product')),
            ],
            options={
                'ordering': ('-is_feature',),
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('language', shared.custom_model_fields.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], default='az', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attribute', to='store.category')),
            ],
        ),
    ]
