# Generated by Django 4.2.6 on 2024-01-28 09:56

import apps.store.models
from django.db import migrations
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cover_image',
            field=shared.custom_model_fields.WEBPField(upload_to=apps.store.models.brand_image_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=shared.custom_model_fields.WEBPField(upload_to=apps.store.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to=apps.store.models.collection_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to=apps.store.models.product_image_path),
        ),
    ]
