# Generated by Django 4.2.6 on 2024-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_brand_cover_image_alter_category_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('SQUARE_METER', 'Square Meter'), ('NUMBER', 'Number'), ('BOX', 'Box')], default='NUMBER', max_length=50),
        ),
    ]
