# Generated by Django 4.2.6 on 2023-11-05 16:09

from django.db import migrations, models
import django.db.models.deletion
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('language', shared.custom_model_fields.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], default='az', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attribute', to='store.category')),
            ],
        ),
    ]
