# Generated by Django 4.2.6 on 2024-04-21 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_quantity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
