# Generated by Django 4.2.6 on 2023-11-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_categoryattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattribute',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
