# Generated by Django 4.2.6 on 2023-11-12 09:37

from django.db import migrations, models
import django.db.models.deletion
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_categoryattribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', shared.custom_model_fields.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], default='az', max_length=2)),
                ('text', shared.custom_model_fields.TextUploadingField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_information', to='store.product')),
            ],
        ),
    ]
