# Generated by Django 4.2.6 on 2023-11-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('SQUARE_METER', 'Square Meter'), ('NUMBER', 'Number')], default='NUMBER', max_length=50),
        ),
    ]
