# Generated by Django 4.2.6 on 2023-11-17 09:15

from django.db import migrations
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_quantity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=shared.custom_model_fields.CreatedAtField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=shared.custom_model_fields.UpdatedAtField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=shared.custom_model_fields.CreatedAtField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=shared.custom_model_fields.UpdatedAtField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=shared.custom_model_fields.CreatedAtField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=shared.custom_model_fields.UpdatedAtField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=shared.custom_model_fields.CreatedAtField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=shared.custom_model_fields.UpdatedAtField(auto_now=True),
        ),
    ]
