# Generated by Django 4.2.6 on 2023-11-28 20:51

import apps.store.models
from django.db import migrations, models
import django.db.models.deletion
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.store.models.product_model_image_path)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Models',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='store.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='store.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_model', to='store.productmodel'),
        ),
    ]
