# Generated by Django 4.2.6 on 2023-10-22 18:12

from django.db import migrations, models
import shared.custom_model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', shared.custom_model_fields.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], default='az', max_length=2)),
                ('privacy_policy', shared.custom_model_fields.TextField(blank=True, null=True)),
                ('about', shared.custom_model_fields.TextField(blank=True, null=True)),
                ('created_at', shared.custom_model_fields.CreatedAtField(auto_now_add=True)),
                ('updated_at', shared.custom_model_fields.UpdatedAtField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Texts',
            },
        ),
    ]
