# Generated by Django 4.2.6 on 2023-10-23 19:07

from django.db import migrations
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='delivery_policy',
            field=shared.custom_model_fields.TextField(blank=True, null=True),
        ),
    ]
