# Generated by Django 4.2.6 on 2023-10-24 19:58

from django.db import migrations, models
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitetext_delivery_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', shared.custom_model_fields.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], default='az', max_length=2)),
                ('address', models.TextField()),
                ('work_hours', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Contact Emails',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Contact Phones',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook')], max_length=50)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Social Media links',
            },
        ),
    ]
