# Generated by Django 4.2.6 on 2023-10-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_companyinfo_contactemail_contactphone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='work_hours',
            new_name='working_hours',
        ),
    ]
