# Generated by Django 4.2.6 on 2023-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_work_hours_companyinfo_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('privacy_policy_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('delivery_policy_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name_plural': 'Site Images',
            },
        ),
    ]
