# Generated by Django 4.2.6 on 2023-11-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('PINTEREST', 'Pinterest'), ('GOOGLEPLUS', 'GooglePlus')], max_length=50),
        ),
    ]
