# Generated by Django 4.2.6 on 2023-11-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'verbose_name_plural': 'Social Media Links'},
        ),
    ]
