# Generated by Django 4.2.6 on 2024-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_socialmedialink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('PINTEREST', 'Pinterest'), ('GOOGLEPLUS', 'GooglePlus'), ('TIKTOK', 'TikTok')], max_length=50),
        ),
    ]
