# Generated by Django 4.2.6 on 2024-01-28 09:56

import apps.main.models
from django.db import migrations
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=shared.custom_model_fields.WEBPField(upload_to=apps.main.models.banner_image_path),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='about_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='contact_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='delivery_policy_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='privacy_policy_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to='site/'),
        ),
    ]
