# Generated by Django 4.2.6 on 2024-02-18 10:13

import apps.main.models
from django.db import migrations
import shared.custom_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_banner_image_alter_siteimage_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='about_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to=apps.main.models.site_image_path),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='contact_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to=apps.main.models.site_image_path),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='delivery_policy_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to=apps.main.models.site_image_path),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='privacy_policy_image',
            field=shared.custom_model_fields.WEBPField(blank=True, null=True, upload_to=apps.main.models.site_image_path),
        ),
    ]
