# Generated by Django 3.2 on 2026-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_siteimage_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
